### ISSUE TITLE
Where are the models available in Groq?

### ISSUE THREAD

**Issue by suizideFloat** [jgravelle/Groqqle#4]
Guys, nice project, but llama2 ? and mixtral only? There is Llama3.1 in different flavors and Llama3 availbale on groq. Please add that to the code.

**Comment by jgravelle** [comment]
When running on the Streamlit hosted site, that'll happen.  The summaries can be unavailable as well.  This doesn't happen when run locally.

It has to do with Streamlit's IPs getting flagged as potential D.O.S. agents due to the volume of traffic that comes from them.  Please see the latest video.

Thanks for the feedback and your interest...!

**Comment by suizideFloat** [comment]
What do you mean by that? I run it locally (dockerized). And see the image to verify my claim.
![Screenshot](https://github.com/user-attachments/assets/bff46bf3-ecef-4d08-967c-1de110121ef1)

**Comment by jgravelle** [comment]
Pull down the latest version and try again ...
